title: Tony Joanes
description: My repository of helpful things for a softare engineer
theme: just-the-docs

url: https://tonyjoanes.github.io/

aux_links:
  Template Repository: https://github.com/tonyjoanes/tonyjoanes.github.io/
